### ISSUE TITLE
Plan relases

### ISSUE THREAD

**Issue by patnr** [nansencenter/DAPPER#24]
Make roadmaps for v1.2 and v2.

Ideally, this should consist of "enhancement" issues that get tagged with the "project" labels v1.2 and v2.

Discuss

**Comment by patricknraanes** [comment]
@yumengch I'm guessing you've noticed I've moved the TODOs into issues. This is so that they can be tracked with the "Projects" tab, and so that we can easily know what the other person(s) is/will work on.

Since you're already pretty much creating issues before PRs I don't think this will change much for you. But I think this format has the potential to further facilitate the communication! For example, if you wish, you can add your own TODOs as individual issues, thereby opening them for discussion possibly ahead of time.

**Comment by yumengch** [comment]
@patricknraanes Thanks! This is good project management practice. I will follow.
