### ISSUE TITLE
Liveplotting in Jupyter notebook ?

### ISSUE THREAD

**Issue by atantet** [nansencenter/DAPPER#46]
Is there a way to have the live plots work in a Jupyter notebook, or at least to have the replays?
Maybe something with the matplotlib backend?

Sorry if it is a naive question, I find this package amazing and am only learning to use it.

**Comment by patricknraanes** [comment]
Hi! Thanks for the kind words!

I don't think actual live plotting is possible, because I don't think the mpl backends on Jupyter allow for it, at least not very well.

However, the replays work fine. 

You can see it in action here:
https://github.com/nansencenter/DA-tutorials
In the README, click on "open in colab". In the first chapter (T1) there is an example.
Beware that it's using and older version of DAPPER, so the syntax has probably changed somewhat (ref `examples/basic_1.py`)

**Comment by atantet** [comment]
Thanks for the very quick reply.
I can see that replays indeed work on Colab, but when I try to run examples/basic_1.py converted as a notebook, I do not get the plot.
Maybe it's my own configuration.
I will continue with my own plots, but if it can help, attached is my `conda list` :

[list.txt](https://github.com/nansencenter/DAPPER/files/6021518/list.txt)

**Comment by patricknraanes** [comment]
I think it's not your config. Some settings have changed, since the version of DAPPER that is being used on Colab. I cannot get the liveplotting or replays to work within Jupyter either. I'm sorry, but atm. I'm not sure what the fix is. Will try to get back to you some other time, but I cannot say when exactly.

**Comment by atantet** [comment]
OK, no problem, I'll continue to work with my own static plots. Thanks for the feedback!

**Comment by patricknraanes** [comment]
It is working now. It's not perfect, but it seems the best possible until [this](https://github.com/matplotlib/matplotlib/issues/9606) is resolved.

**Comment by atantet** [comment]
Thanks a lot !
