### ISSUE TITLE
Connecting an external dynamical model

### ISSUE THREAD

**Issue by Balinus** [nansencenter/DAPPER#85]
Hello!

Thanks for this library. I was wondering, before I go ahead, if it was possible to launch an external dynamical model (compiled in C++ or Matlab source code)? The model does not exist in Python. Is there a template somewhere in the documentation for such a use case?

Thanks!

**Comment by patricknraanes** [comment]
Hi, there is an example of connecting to Fortran90 code, see `dapper/mods/QG`.

I have not interfaced with C or Matlab myself, but it's supposed to be one of the things Python is good at, so should definitely be possible. Otherwise just try to follow the guidelines from the [docs](https://nansencenter.github.io/DAPPER/dapper/mods/index.html)

**Comment by Balinus** [comment]
Thanks! That should be possible then. I read a little bit about interfacing C and Matlab and there are definitely solutions. 

Thanks again!
